services:
  - type: web
    name: noteapi-fastapi
    runtime: docker
    dockerfilePath: ./Dockerfile.fastapi
    envVars:
      - key: MONGO_URI
        sync: false
      - key: OAUTH_GITHUB_CLIENT_ID
        sync: false
      - key: OAUTH_GITHUB_CLIENT_SECRET
        sync: false
      - key: OAUTH_REDIRECT_URI
        sync: false
      - key: OAUTH_GOOGLE_CLIENT_ID
        sync: false
      - key: OAUTH_GOOGLE_CLIENT_SECRET
        sync: false
      - key: OAUTH_GOOGLE_REDIRECT_URI
        sync: false
      - key: OAUTH_GOOGLE_WORKSPACE_CLIENT_ID
        sync: false
      - key: OAUTH_GOOGLE_WORKSPACE_CLIENT_SECRET
        sync: false
      - key: OAUTH_GOOGLE_WORKSPACE_REDIRECT_URI
        sync: false
      - key: OAUTH_GOOGLE_WORKSPACE_DOMAIN
        sync: false
      - key: OAUTH_STREAMLIT_URL
        sync: false
      - key: BASIC_AUTH_USERNAME
        sync: false
      - key: BASIC_AUTH_PASSWORD
        sync: false
      - key: ADMIN_USERNAMES
        sync: false
      - key: AUTH_DISABLED
        value: "false"

  - type: web
    name: noteapi-streamlit
    runtime: docker
    dockerfilePath: ./Dockerfile.streamlit
    envVars:
      - key: API_BASE_URL
        sync: false
      - key: PUBLIC_API_BASE_URL
        sync: false
      - key: PUBLIC_STREAMLIT_URL
        sync: false